version: '3'
services:
  events:
    build: ./events
    ports:
      - "5000:5000"
    restart: always
    networks:
      - football-network
    env_file:
      - .env
  odds:
    build: ./odds
    ports:
      - "5050:5050"
    restart: always
    networks:
      - football-network
    env_file:
      - .env
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - football-network

networks:
  football-network: